// SPDX-License-Identifier: Apache-2.0
#define _POSIX_C_SOURCE 200809L
#define GC_THREADS
#define GC_NO_THREAD_REDIRECTS
#include "tdf3.h"
#include <gc/gc.h>
#include <pthread.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static tdf3_bytes text(const char *s){return(tdf3_bytes){(const uint8_t *)s,strlen(s)};}
static tdf3_config config(void){return(tdf3_config){.PlatformURL=text("http://localhost:8080"),.KASURL=text("http://localhost:8080/kas"),.IssuerURL=text("http://localhost:8888/auth/realms/opentdf"),.ClientID=text("opentdf-sdk"),.ClientSecret=text("secret"),.AllowHTTP=true};}
static const uint8_t input[]={0,255,128,0,1};
static tdf3_result encrypted;
static void check(int rc,tdf3_error *error){if(rc)fprintf(stderr,"SDK rc%d code%.*s message%.*s\n",rc,(int)error->Code.length,error->Code.data,(int)error->Message.length,error->Message.data);assert(!rc);tdf3_error_free(error);}
static void *first(void *arg){bool async=*(bool *)arg;tdf3_config c=config();tdf3_bytes attr=text("https://example.com/attr/attr1/value/value1");tdf3_encrypt_options o={.Attributes=&attr,.AttributesLength=1};tdf3_error error={0};printf("first caller started; GC initialized=%d registered=%d async=%d\n",GC_is_init_called(),GC_thread_is_registered(),async);
 if(async){tdf3_operation *op=tdf3_encrypt_submit(&c,(tdf3_bytes){input,sizeof input},&o,NULL,&error);assert(op);assert(tdf3_operation_drive(op,-1));check(tdf3_operation_take(op,&encrypted,&error),&error);tdf3_operation_destroy(&op);assert(!op);}else check(tdf3_encrypt(&c,(tdf3_bytes){input,sizeof input},&o,NULL,&encrypted,&error),&error);
 printf("first caller settled; owned bytes=%zu registered=%d\n",encrypted.Payload.length,GC_thread_is_registered());return NULL;}
static void *collect(void *unused){(void)unused;struct GC_stack_base sb;assert(GC_get_stack_base(&sb)==GC_SUCCESS);int rc=GC_register_my_thread(&sb);printf("collection helper registration=%d (success=%d duplicate=%d)\n",rc,GC_SUCCESS,GC_DUPLICATE);assert(rc==GC_SUCCESS||rc==GC_DUPLICATE);for(int i=0;i<3;i++){puts("forcing collection");GC_gcollect();puts("collection returned");}if(rc==GC_SUCCESS)assert(GC_unregister_my_thread()==GC_SUCCESS);return NULL;}
static void *registered_first(void *arg){struct GC_stack_base sb;assert(GC_get_stack_base(&sb)==GC_SUCCESS);assert(GC_register_my_thread(&sb)==GC_SUCCESS);assert(GC_thread_is_registered());first(arg);assert(GC_thread_is_registered());assert(GC_unregister_my_thread()==GC_SUCCESS);return NULL;}
static void overlap(void){setbuf(stdout,NULL);assert(!GC_is_init_called());tdf3_config c=config();tdf3_bytes attr=text("https://example.com/attr/attr1/value/value1");tdf3_encrypt_options o={.Attributes=&attr,.AttributesLength=1};tdf3_operation *ops[6];tdf3_result outputs[6]={0};tdf3_error e={0};for(int i=0;i<6;i++){ops[i]=tdf3_encrypt_submit(&c,(tdf3_bytes){input,sizeof input},&o,NULL,&e);assert(ops[i]);}assert(tdf3_operation_drive(ops[0],-1));check(tdf3_operation_take(ops[0],&outputs[0],&e),&e);tdf3_operation_destroy(&ops[0]);pthread_t collector;assert(!pthread_create(&collector,NULL,collect,NULL));for(int i=1;i<6;i++){assert(tdf3_operation_drive(ops[i],-1));check(tdf3_operation_take(ops[i],&outputs[i],&e),&e);tdf3_operation_destroy(&ops[i]);}assert(!pthread_join(collector,NULL));assert(!GC_thread_is_registered());for(int i=0;i<6;i++){tdf3_result r={0};check(tdf3_decrypt(&c,(tdf3_bytes){outputs[i].Payload.data,outputs[i].Payload.length},NULL,&r,&e),&e);assert(r.Payload.length==sizeof input&&!memcmp(r.Payload.data,input,sizeof input));tdf3_result_free(&r);tdf3_result_free(&outputs[i]);}puts("PASS first-async overlapping callers and forced collection during queued/active calls with owned results and no caller registration");return;}
int main(int argc,char **argv){assert(argc==2);setbuf(stdout,NULL);if(!strcmp(argv[1],"overlap")){overlap();return 0;}bool external=strstr(argv[1],"external")!=NULL;bool registered=strstr(argv[1],"registered")!=NULL;bool async=strstr(argv[1],"async")!=NULL;bool main_caller=!strncmp(argv[1],"main-",5);if(external){GC_INIT();assert(GC_thread_is_registered());if(registered)GC_allow_register_threads();}else assert(!GC_is_init_called());printf("fresh extended mode=%s external main initialized=%d registered=%d\n",argv[1],GC_is_init_called(),GC_thread_is_registered());pthread_t caller;if(main_caller)first(&async);else{assert(!pthread_create(&caller,NULL,registered?registered_first:first,&async));assert(!pthread_join(caller,NULL));}assert(GC_thread_is_registered()==external);puts("first caller joined; external registration ownership preserved");
 for(int i=0;i<6;i++){tdf3_config c=config();tdf3_result r={0};tdf3_error e={0};assert(!tdf3_decrypt(&c,(tdf3_bytes){encrypted.Payload.data,encrypted.Payload.length},NULL,&r,&e));assert(r.Payload.length==sizeof input&&!memcmp(r.Payload.data,input,sizeof input));tdf3_result_free(&r);tdf3_error_free(&e);pthread_t collector;assert(!pthread_create(&collector,NULL,collect,NULL));assert(!pthread_join(collector,NULL));assert(GC_thread_is_registered()==external);}
 tdf3_config c=config();tdf3_result r={0};tdf3_error e={0};uint8_t invalid[]={1,2,3};assert(tdf3_decrypt(&c,(tdf3_bytes){invalid,3},NULL,&r,&e)==1&&!r.Payload.data);tdf3_error_free(&e);assert(!tdf3_decrypt(&c,(tdf3_bytes){encrypted.Payload.data,encrypted.Payload.length},NULL,&r,&e));tdf3_result_free(&r);tdf3_result_free(&encrypted);assert(GC_thread_is_registered()==external);puts("PASS initialization/registered caller ownership, repeated calls/forced collection, declared error and recovery");return 0;}
