// SPDX-License-Identifier: Apache-2.0
#define _POSIX_C_SOURCE 200809L
#include "goalchemy.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static void write(const char *root,const char *name,const void *data,size_t n){char path[4096];snprintf(path,sizeof path,"%s/%s",root,name);FILE *f=fopen(path,"wb");assert(f);assert(!n||fwrite(data,1,n,f)==n);assert(!fclose(f));}
int main(int argc,char **argv){assert(argc==5);gxc_value out={0};gxc_error error={0};char number[64];uint8_t invalid[]={'X','-','T',0,'a'};gxc_value headers[]={{.kind=GXC_BYTES,.bytes=invalid,.length=sizeof invalid},{.kind=GXC_BYTES,.bytes=(uint8_t *)"1",.length=1}};gxc_value args[]={{.kind=GXC_BYTES,.bytes=(uint8_t *)argv[1],.length=strlen(argv[1])},{.kind=GXC_LIST},{.kind=GXC_INT,.integer=atoll(argv[3])}};if(!strcmp(argv[2],"nul-header")){args[1].items=headers;args[1].length=2;}else if(!strcmp(argv[2],"nul-value")){headers[0]=(gxc_value){.kind=GXC_BYTES,.bytes=(uint8_t *)"X-Test",.length=6};headers[1]=(gxc_value){.kind=GXC_BYTES,.bytes=invalid,.length=sizeof invalid};args[1].items=headers;args[1].length=2;}else if(!strcmp(argv[2],"explicit-gzip")||!strcmp(argv[2],"explicit-custom")||!strcmp(argv[2],"empty-encoding")||!strcmp(argv[2],"range")){const char *name=!strcmp(argv[2],"range")?"Range":"Accept-Encoding";const char *value=!strcmp(argv[2],"range")?"bytes=0-100":!strcmp(argv[2],"explicit-custom")?"br, gzip":!strcmp(argv[2],"empty-encoding")?"":"gzip";headers[0]=(gxc_value){.kind=GXC_BYTES,.bytes=(uint8_t *)name,.length=strlen(name)};headers[1]=(gxc_value){.kind=GXC_BYTES,.bytes=(uint8_t *)value,.length=strlen(value)};args[1].items=headers;args[1].length=2;}int rc=goalchemy_invoke("Probe",args,3,NULL,&out,&error);int n=snprintf(number,sizeof number,"%d\n",rc);write(argv[4],"kind",number,(size_t)n);write(argv[4],"message",error.message.bytes,error.message.length);const gxc_value *body=gxc_field(&out,"Body"),*list=gxc_field(&out,"Headers");write(argv[4],"body",body->bytes,body->length);n=snprintf(number,sizeof number,"%lld\n",(long long)gxc_field(&out,"Status")->integer);write(argv[4],"status",number,(size_t)n);char path[4096];snprintf(path,sizeof path,"%s/headers",argv[4]);FILE *f=fopen(path,"wb");assert(f);for(size_t i=0;i<list->length;i++){assert(list->items[i].kind==GXC_BYTES);assert(fwrite(list->items[i].bytes,1,list->items[i].length,f)==list->items[i].length);fputc('\n',f);}assert(!fclose(f));gxc_value_free(&out);gxc_error_free(&error);return 0;}
