// Actual Chromium imports the compiled portable package; all OAuth credentials
// remain inside this host fixture. No original SDK is imported in the bundle.
import{createServer}from'node:http';import{readFile,writeFile,mkdir}from'node:fs/promises';import{resolve}from'node:path';import{execFileSync,spawnSync}from'node:child_process';import{createHash}from'node:crypto';
import{build}from'../../../../goalchemy/out/typescript-host-operations/tooling/node_modules/esbuild/lib/main.js';import{chromium}from'../../../../goalchemy/out/typescript-host-operations/tooling/node_modules/playwright/index.mjs';import{acquireToken}from'./token-provider.mjs';
const sdk=resolve(import.meta.dirname,'../../..'),stage=process.argv[2]??'basic';if(!['basic','ec','dpop'].includes(stage))throw new Error('stage');const base=resolve(sdk,'.local/typescript-tdf-library'),run=resolve(base,'browser-'+stage);await mkdir(run,{recursive:true});
const result=await build({entryPoints:[resolve(sdk,'../goalchemy/out/typescript-tdf-library/sdk/dist/index.js')],bundle:true,platform:'browser',format:'esm',write:false,metafile:true});for(const file of Object.keys(result.metafile.inputs)){const source=await readFile(file,'utf8');if(/node:|\bBuffer\b|\bprocess\b/.test(source))throw new Error('Node dependency '+file);}await writeFile(resolve(run,'browser-graph.json'),JSON.stringify(result.metafile,null,2));
const rows=[],transport=[];let brokerRequests=0;
function hash(b){return createHash('sha256').update(b).digest('hex');}
async function configure(wrap='rsa:2048',session='rsa:2048',auth='ES256'){
 const cfg={PlatformURL:'http://localhost:8080',KASURL:'http://localhost:8080/kas',IssuerURL:'http://localhost:8888/auth/realms/opentdf',AllowHTTP:true,KASAlgorithm:wrap,SessionAlgorithm:session,AuthAlgorithm:auth,DPoP:stage==='dpop',AllowedKAS:[{URL:'http://localhost:8080/kas',APIBaseURL:'http://localhost:8080'}]};
 if(stage!=='basic'){cfg.KASPublicKeyPEM=await readFile(resolve(base,'ec',wrap.slice(0,2)+'-public.pem'),'utf8');cfg.KID=wrap.startsWith('rsa')?'profile-r1':'profile-e1';cfg.AuthPrivateKeyPEM=await readFile(resolve(base,'auth-'+auth+'.pem'),'utf8');}
 return cfg;
}
const server=createServer(async(req,res)=>{try{
 if(req.url==='/sdk.js'){res.setHeader('Content-Type','text/javascript');res.end(result.outputFiles[0].text);return;}
 if(['/token','/token-mismatch'].includes(req.url)&&req.method==='POST'){brokerRequests++;const chunks=[];for await(const b of req)chunks.push(b);const config=JSON.parse(Buffer.concat(chunks));if(config.ClientSecret||config.ClientID)throw new Error('browser carried credentials');const controller=new AbortController();res.on('close',()=>controller.abort());const token=await acquireToken(config,controller.signal,req.url==='/token-mismatch'?'mismatched-provider':'browser');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({...token,expiresAt:String(token.expiresAt)}));return;}
 res.setHeader('Content-Type','text/html');res.end('<script type="module">import * as sdk from "/sdk.js";window.sdk=sdk;window.ready=true;</script>');
 }catch{res.writeHead(500);res.end('fixture provider failed');}});
await new Promise((r,j)=>{server.once('error',j);server.listen(5173,'localhost',r);});let browser;
function invoke(label,args,required=true){const response=spawnSync(args[0],args.slice(1),{cwd:sdk,timeout:120000,encoding:'buffer'});const status=response.status??-1;if(required&&status!==0)throw new Error(label+' failed '+status);return writeFile(resolve(run,label+'.status'),String(status)+'\n').then(()=>({status,output:response.stdout,diagnostic:response.stderr}));}
try{
 let executablePath=process.env.GOALCHEMY_CHROME;for(const n of ['google-chrome','chromium','chromium-browser']){if(executablePath)break;try{executablePath=execFileSync('which',[n],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}catch{}}
 browser=await chromium.launch({...(executablePath?{executablePath}:{}),headless:true,args:['--no-sandbox']});console.log('Browser',await browser.version());const page=await browser.newPage();await page.goto('http://localhost:5173');await page.waitForFunction(()=>window.ready);
 await page.evaluate(()=>{window.observations=[];const original=window.fetch;window.fixtureNativeFetch=original;window.fetch=async(...args)=>{const response=await original(...args);if(response.ok&&String(args[0]).includes('/Rewrap')){const init=args[1];window.fixtureAcceptedRequest={url:String(args[0]),headers:new Headers(init.headers),body:new Uint8Array(init.body)};}window.observations.push({url:String(args[0]).split('?')[0],status:response.status,type:response.type,nonceReadable:response.headers.get('DPoP-Nonce')!==null});return response;};window.options=config=>({tokenProvider:async signal=>{const response=await fetch('/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config),signal});if(!response.ok)throw new Error('provider failed');const t=await response.json();return {...t,expiresAt:BigInt(t.expiresAt)};}});});
 const cases={empty:new Uint8Array(),binary:Uint8Array.from([...Array.from({length:768},(_,i)=>i%256),0,255]),exact:new Uint8Array(16384).map((_,i)=>[0,255,128,7][i%4]),multiple:new Uint8Array(32772).map((_,i)=>[0,255,128,7][i%4]),hs256:new Uint8Array(32772).map((_,i)=>[0,255,128,7][i%4]),metadata:new TextEncoder().encode(stage==='basic'?'metadata case':'metadata bytes'),'empty-metadata':new TextEncoder().encode('empty metadata')};
 const combinations=stage==='basic'?[['rsa:2048','rsa:2048','ES256']]:['rsa:2048','ec:secp256r1'].flatMap(w=>['rsa:2048','ec:secp256r1'].flatMap(s=>['ES256','RS256'].map(a=>[w,s,a])));
 for(const [wrap,session,auth]of combinations){const cfg=await configure(wrap,session,auth);await writeFile(resolve(run,'config.json'),JSON.stringify({...cfg,ClientID:'opentdf-sdk',ClientSecret:'secret'}),{mode:0o600});
  for(const[name,input]of Object.entries(cases)){
   const label=wrap.slice(0,2)+'-'+session.slice(0,2)+'-'+auth.toLowerCase()+'-'+name,metadata=name==='metadata'?new TextEncoder().encode('{"source":"independent metadata","count":7}'):new Uint8Array();await writeFile(resolve(run,label+'.input'),input);
   const encrypted=await page.evaluate(async({cfg,input,name,metadata})=>{const opts={Attributes:['https://example.com/attr/attr1/value/value1'],SegmentSize:16384n,HasSegmentSize:true,SegmentHashAlgorithm:name==='hs256'?'HS256':'GMAC',Metadata:new Uint8Array(metadata),IncludeMetadata:name==='metadata'||name==='empty-metadata',MimeType:'application/日本語'};return Array.from(await window.sdk.encrypt(cfg,new Uint8Array(input),opts,window.options(cfg)));},{cfg,input:Array.from(input),name,metadata:Array.from(metadata)});await writeFile(resolve(run,label+'.generated.tdf'),Uint8Array.from(encrypted));
   const reference=resolve(sdk,'.local/go-tdf-library/stock-go');await invoke('stock-go-decrypt-'+label,[reference,run,'decrypt',label,session]);const gout=await readFile(resolve(run,label+'.stock-go.out')),gmeta=await readFile(resolve(run,label+'.stock-go.metadata'));if(hash(gout)!==hash(input)||hash(gmeta)!==hash(metadata))throw new Error('stock Go byte mismatch');rows.push({producer:'generated-typescript-browser',consumer:'stock-go',case:name,wrap,session,auth,payload_sha256:hash(input),metadata_sha256:hash(metadata)});
   if(stage!=='dpop'){const out=resolve(run,label+'.stock-web.out');await invoke('stock-web-decrypt-'+label,['node',resolve(sdk,'.local/web-cli/bin/opentdf.mjs'),'decrypt',resolve(run,label+'.generated.tdf'),'--rewrapKeyType',session,'--allowList','http://localhost:8080','--output',out,'--platformUrl','http://localhost:8080','--kasEndpoint','http://localhost:8080/kas','--oidcEndpoint','http://localhost:8888/auth/realms/opentdf','--clientId','opentdf-sdk','--clientSecret','secret','--logLevel','error']);if(hash(await readFile(out))!==hash(input))throw new Error('stock Web byte mismatch');rows.push({producer:'generated-typescript-browser',consumer:'stock-web',case:name,wrap,session,auth,metadata:'stock reader limitation'});}
   const sourceStage=stage==='basic'?'basic':'ec';const producerCase=stage==='basic'?name:wrap.slice(0,2)+'-'+name;let producerRun=resolve(base,sourceStage);let producerName=producerCase;if(stage!=='basic'&&name==='empty-metadata'){producerRun=stage==='dpop'?resolve(base,'browser-ec'):run;producerName=label;if(stage==='ec'){await invoke('stock-go-encrypt-'+label,[reference,run,'encrypt',label,wrap]);await invoke('stock-web-encrypt-'+label,['node',resolve(sdk,'tests/interop/generatedlibrary/web-fixture.mjs'),sdk,resolve(run,label+'.input'),resolve(run,label+'.web.tdf'),'GMAC','','https://example.com/attr/attr1/value/value1',wrap,cfg.KID,resolve(base,'ec',wrap.slice(0,2)+'-public.pem')]);}}
   for(const producer of ['go','web']){const archive=await readFile(resolve(producerRun,producerName+'.'+producer+'.tdf'));const decrypted=await page.evaluate(async({cfg,archive})=>{const result=await window.sdk.decrypt(cfg,new Uint8Array(archive),window.options(cfg));return {payload:Array.from(result.Payload),metadata:Array.from(result.Metadata??[]),hasMetadata:result.HasMetadata,manifest:result.ManifestJSON};},{cfg,archive:Array.from(archive)});if(hash(Uint8Array.from(decrypted.payload))!==hash(input)||hash(Uint8Array.from(decrypted.metadata))!==hash(metadata))throw new Error('browser decrypted mismatch '+producer+' '+name);rows.push({producer:'stock-'+producer+(stage==='dpop'?'-format-under-bearer':''),consumer:'generated-typescript-browser',case:name,wrap,session,auth,payload_sha256:hash(input),metadata_sha256:hash(metadata)});}
   const own=await page.evaluate(async({cfg,archive})=>{const r=await window.sdk.decrypt(cfg,new Uint8Array(archive),window.options(cfg));return {p:Array.from(r.Payload),m:Array.from(r.Metadata??[]),presence:r.HasMetadata,text:r.ManifestJSON};},{cfg,archive:encrypted});if(hash(Uint8Array.from(own.p))!==hash(input)||hash(Uint8Array.from(own.m))!==hash(metadata)||own.presence!==(name==='metadata'||name==='empty-metadata')||!own.text.includes('日本語'))throw new Error('browser own output/UTF8');
   console.log('PASS real browser',stage,wrap,session,auth,name);
  }
 }
 const cfg=await configure(),archive=await readFile(resolve(base,stage==='basic'?'basic':'ec',stage==='basic'?'binary.go.tdf':'rs-binary.go.tdf'));const negatives=[];
 for(const mode of ['invalid-token','expired-token','provider-reject','malformed','active-cancel']){const output=await page.evaluate(async({cfg,archive,mode})=>{let options;if(mode==='active-cancel'){const ctrl=new AbortController();options={signal:ctrl.signal,tokenProvider:async signal=>{ctrl.abort('browser cancel');if(signal.aborted)throw new Error('canceled');await new Promise(r=>signal.addEventListener('abort',r,{once:true}));throw new Error('canceled');}};}else if(mode==='provider-reject')options={tokenProvider:async()=>{throw new Error('reject');}};else options={tokenProvider:async()=>({value:mode==='invalid-token'?'bad':'expired',scheme:cfg.DPoP?'DPoP':'Bearer',expiresAt:BigInt(Math.floor(Date.now()/1000)+(mode==='expired-token'?-1:300))})};try{await window.sdk.decrypt(cfg,mode==='malformed'?new Uint8Array([0]):new Uint8Array(archive),options);return {accepted:true};}catch(e){return {accepted:false,kind:e.kind,code:e.code};}},{cfg,archive:Array.from(archive),mode});if(output.accepted)throw new Error('browser negative accepted');negatives.push({case:mode,...output});}
 // Fresh negative mutations use the current profile's independently retained
 // archive, so integrity failures reach the real active KAS before validation.
 const seed=resolve(base,stage==='basic'?'basic':'ec',stage==='basic'?'binary.generated.tdf':'rs-es256-binary.generated.tdf');await invoke('negative-fixtures',['python3',resolve(sdk,'tests/interop/generatedtypescript/negative-fixtures.py'),seed,run]);
 for(const [name,code]of [['tampered','integrity'],['root-tamper','integrity'],['unsupported-root','unsupported_manifest'],['unsupported-assertion','unsupported_manifest'],['untrusted','kas_not_allowed']]){const bad=await readFile(resolve(run,name+'.tdf'));const failure=await page.evaluate(async({cfg,archive})=>{try{await window.sdk.decrypt(cfg,new Uint8Array(archive),window.options(cfg));return null;}catch(e){return {kind:e.kind,code:e.code};}},{cfg,archive:Array.from(bad)});if(failure?.code!==code)throw new Error('browser negative '+name+' expected '+code+' got '+failure?.code);negatives.push({case:name,...failure});}
 for(const [wrap,session,auth]of combinations){const deniedCfg=await configure(wrap,session,auth);const failure=await page.evaluate(async cfg=>{const archive=await window.sdk.encrypt(cfg,new Uint8Array([1]),{Attributes:['https://example.com/attr/attr1/value/value2']},window.options(cfg));try{await window.sdk.decrypt(cfg,archive,window.options(cfg));return null;}catch(e){return {kind:e.kind,code:e.code};}},deniedCfg);if(failure?.code!=='rewrap_failed')throw new Error('browser real denied policy');negatives.push({case:'policy-denied',wrap,session,auth,...failure});}
 const snapshot=await page.evaluate(async cfg=>{class BorrowingBytes extends Uint8Array{slice(start=0,end=this.length){return this.subarray(start,end);}}const payload=new BorrowingBytes([0,255,1,7]),metadata=new BorrowingBytes([128,255,0]);const pending=window.sdk.encrypt(cfg,payload,{Metadata:metadata,IncludeMetadata:true},window.options(cfg));payload.fill(44);metadata.fill(44);const archive=await pending,result=await window.sdk.decrypt(cfg,archive,window.options(cfg));return {payload:Array.from(result.Payload),metadata:Array.from(result.Metadata),presence:result.HasMetadata};},cfg);if(String(snapshot.payload)!=='0,255,1,7'||String(snapshot.metadata)!=='128,255,0'||!snapshot.presence)throw new Error('browser SDK subclass snapshot');
 if(stage==='dpop'){
  for(const auth of ['ES256','RS256']){const mismatchCfg=await configure('rsa:2048','rsa:2048',auth);const failure=await page.evaluate(async({cfg,archive})=>{const opts={tokenProvider:async signal=>{const response=await fetch('/token-mismatch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg),signal});const token=await response.json();return {...token,expiresAt:BigInt(token.expiresAt)};}};try{await window.sdk.decrypt(cfg,new Uint8Array(archive),opts);return null;}catch(e){return {kind:e.kind,code:e.code};}},{cfg:mismatchCfg,archive:Array.from(archive)});if(failure?.code!=='token_binding')throw new Error('browser mismatched DPoP binding');negatives.push({case:'mismatched-provider-auth-key',auth,...failure});}
  const replay=await page.evaluate(async()=>{const request=window.fixtureAcceptedRequest;if(!request)throw new Error('no successful real request captured');const response=await window.fixtureNativeFetch(request.url,{method:'POST',headers:request.headers,body:request.body,redirect:'manual',credentials:'omit'});return {status:response.status,nonceReadable:response.headers.get('DPoP-Nonce')!==null};});if(replay.status!==401)throw new Error('real KAS accepted replay '+replay.status);negatives.push({case:'actual-accepted-proof-replay',...replay});
 }
 const observed=await page.evaluate(()=>window.observations);transport.push(...observed);if(stage==='dpop'&&!observed.some(o=>o.nonceReadable&&o.url.includes('8080')))throw new Error('actual KAS nonce was not readable');
 await writeFile(resolve(run,'results.json'),JSON.stringify({stage,scope:'actual browser generated SDK and real KAS with host token broker; no browser credential secret',pairs:rows,negatives,brokerRequests,snapshot,graphInputs:Object.keys(result.metafile.inputs).length,transport},null,2));console.log('PASS browser matrix',rows.length,'comparisons',negatives.length,'negatives',brokerRequests,'native broker calls');
}finally{await browser?.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
